# Generated by Django 6.0 on 2026-01-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='describtion',
            new_name='description',
        ),
    ]
