# Generated by Django 6.0 on 2026-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
