# Generated by Django 6.0 on 2026-02-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restaurant_is_open_alter_order_expected_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('restaurant', 'customer')},
        ),
    ]
