# Generated by Django 6.0 on 2026-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='expected_duration',
            field=models.IntegerField(),
        ),
    ]
