# Generated by Django 6.0 on 2026-02-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_restaurant_address_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.category'),
            preserve_default=False,
        ),
    ]
