# Generated by Django 6.0 on 2026-02-13 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_review_rating_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_rating_per_order_per_customer',
        ),
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_rating_per_order'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer',
        ),
    ]
