# Generated by Django 6.0 on 2026-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_category_is_active_alter_category_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_arrival_time',
            field=models.IntegerField(default=0),
        ),
    ]
