# Generated by Django 6.0 on 2026-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_expected_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
